version: "2.4"

services:
  item-db:
    image: mongo:3
    container_name: item-db
    volumes:
      - app-db:/data/db
    restart: always

  item-app:
    image: ghcr.io/rizkyprayatman/item-app:v1
    container_name: item-app
    ports:
      - "80:8080"
    depends_on:
      - item-db
    restart: always

volumes:
  app-db:
